export const UPDATE_PRODUCT_COUNTER = "UPDATE_PRODUCT_COUNTER";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const ADD_COST_ON_PRODUCT = "ADD_COST_ON_PRODUCT";
export const ADD_IMAGE_ON_PRODUCT = "ADD_IMAGE_ON_PRODUCT";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const IS_FAVORITE_PRODUCT = "IS_FAVORITE_PRODUCT";
